name: CI/CD WorkFlow

on:
  pull_request_target:
    branches: ["main", "dev"]
    types:
      - closed
  workflow_dispatch:

jobs:
  tests:
    name: "Run Tests"
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run tests
        env:
          MEDDLY_DB_STRING: ${{ secrets.MEDDLY_DB_STRING }}
          MEDDLY_FIREBASE_JSON: ${{ secrets.MEDDLY_FIREBASE_JSON }}
          MEDDLY_FIREBASE_KEY: ${{ secrets.MEDDLY_FIREBASE_KEY }}
          MEDDLY_FIREBASE_PRIVATE_KEY: ${{ secrets.MEDDLY_FIREBASE_PRIVATE_KEY }}
          MEDDLY_ENV_NAME: 'production'
        run: |
          pytest

  deploy:
    name: "Deploy to EC2"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Configurar SSH para Main
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST_MAIN }}
      - name: Configurar SSH para Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST_DEV }}
      - name: Pull changes
        run: |
          ssh staging 'cd ~/Meddly && git pull'
      - name: Stop Container
        run: ssh staging 'docker stop meddly-container' || true

      - name: Delete container and image
        run: |
          ssh staging 'docker rm meddly-container' || true
          ssh staging 'docker rmi meddly' || true

      - name: Build image
        run: ssh staging 'cd ~/Meddly && docker build -t meddly .'

      - name: Run container
        run: >
          ssh staging "docker run -d --name meddly -p 80:8000
          --env MEDDLY_DB_STRING='${{ secrets.MEDDLY_DB_STRING }}'
          --env MEDDLY_FIREBASE_JSON='${{ secrets.MEDDLY_FIREBASE_JSON }}'
          --env MEDDLY_FIREBASE_KEY='${{ secrets.MEDDLY_FIREBASE_KEY }}'
          --env MEDDLY_FIREBASE_PRIVATE_KEY='${{ secrets.MEDDLY_FIREBASE_PRIVATE_KEY }}'
          --env MEDDLY_ENV_NAME='production' meddly"
